# -*- coding: utf-8 -*-
"""cafe-reviews-keywords-extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRC6cxh6obDSNC1dwpi7vosGrQY2TeYL
"""

import pandas as pd
import re
from collections import Counter
from math import log

def find_keywords(file_path):
    # Загрузка данных
    df = pd.read_csv(file_path)

    # Стоп-слова
    stop_words = {'и', 'в', 'во', 'не', 'что', 'на', 'я', 'с', 'со', 'как', 'а', 'но',
                  'он', 'она', 'оно', 'они', 'ты', 'вы', 'мы', 'к', 'у', 'по', 'из', 'за',
                  'о', 'об', 'при', 'без', 'до', 'для', 'через', 'над', 'под', 'про', 'же',
                  'бы', 'ли', 'то', 'это', 'весь', 'все', 'всё', 'вся', 'тут', 'там', 'здесь',
                  'очень', 'ещё', 'уже', 'даже', 'быть', 'сказать', 'который', 'этот', 'эта'}

    # Токенизация всех отзывов
    all_docs = []
    for text in df['normalized_text'].fillna(''):
        if not isinstance(text, str) or text.strip() == '':
            all_docs.append([])
            continue
        tokens = [t for t in text.lower().split()
                  if t not in stop_words and len(t) > 2 and re.match(r'^[а-яё]+$', t)]
        all_docs.append(tokens)

    # Вычисление IDF
    doc_freq = Counter()
    for doc in all_docs:
        doc_freq.update(set(doc))

    N = len(all_docs)
    idf = {word: log((N + 1) / (cnt + 1)) + 1 for word, cnt in doc_freq.items()}

    # Извлечение ключевых слов для каждого отзыва
    key_words_list = []
    for tokens in all_docs:
        if not tokens:
            key_words_list.append([])
            continue

        tf = Counter(tokens)
        tfidf = {word: (count/len(tokens)) * idf[word] for word, count in tf.items()}
        top = sorted(tfidf.items(), key=lambda x: x[1], reverse=True)[:3]
        key_words_list.append([(word, round(score, 3)) for word, score in top])

    df['key_words'] = key_words_list
    return df

